insta/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.contrib.auth import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django_registration.backends.one_step.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    # path('logout/', views.logout, {"next_page": '/'}),
    path('', include('photos.urls'))
]

photos/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home, name='landing'),
    path('^myaccount/', views.mine, name='myaccount'),
    path('^myaccount/edit/', views.edit, name='edit'),
    path('^comment/<int:post_id>', views.comment_on, name='comment'),
    path('^user/(?P<user_id>\d+)', views.user, name='aboutuser'),
    path('^like/(?P<post_id>\d+)', views.like, name='like'),
    path('^save/(?P<post_id>\d+)', views.save, name='save'),
    path('^search/(?P<name>.+)', views.find, name='save'),
    path('^follow_or_not/(?P<user_id>\d+)', views.togglefollow, name='follow_or_not'),
    path('^unlike/(?P<post_id>\d+)', views.unlike, name='unlike')
]

if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photos/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, related_name='profile')
    Name = models.TextField(default="Anonymous")
    profile_picture = models.ImageField(
        upload_to='users/', default='users/user.png')
    bio = models.TextField(default="Welcome Me!")

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()

    @classmethod
    def find_profile(cls, name):
        return cls.objects.filter(user__username__icontains=name).all()

    def togglefollow(self, profile):
        if self.following.filter(followee=profile).count() == 0:
            Follows(followee=profile, follower=self).save()
            return True
        else:
            self.following.filter(followee=profile).delete()
            return False

    def like(self, photo):
        if self.mylikes.filter(photo=photo).count() == 0:
            Likes(photo=photo, user=self).save()

    def save_image(self, photo):
        if self.saves.filter(photo=photo).count() == 0:
            Saves(photo=photo, user=self).save()
        else:
            self.saves.filter(photo=photo).delete()

    def unlike(self, photo):
        self.mylikes.filter(photo=photo).all().delete()

    def comment(self, photo, text):
        Comment(text=text, photo=photo, user=self).save()

    def post(self, form):
        image = form.save(commit=False)
        image.user = self
        image.save()

    @property
    def follows(self):
        return [follow.followee for follow in self.following.all()]


class Post(models.Model):
    image = models.ImageField(upload_to='posts/')
    user = models.ForeignKey(
        Profile, on_delete=models.CASCADE, related_name='posts')

    @property
    def get_comments(self):
        return self.comments.all()

    @property
    def count_likes(self):
        return self.photolikes.count()

    class Meta:
        ordering = ["-pk"]


class Comment(models.Model):
    text = models.TextField()
    photo = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(
        Profile, on_delete=models.CASCADE, related_name='comments')


class Likes(models.Model):
    user = models.ForeignKey(
        Profile, on_delete=models.CASCADE, related_name='mylikes')
    photo = models.ForeignKey(Post, on_delete=models.CASCADE,related_name='photolikes')


class Saves(models.Model):
    user = models.ForeignKey(
        Profile, on_delete=models.CASCADE, related_name='saves')
    photo = models.ForeignKey(Post,on_delete=models.CASCADE)

    class Meta:
        ordering = ["-pk"]


class Follows(models.Model):
    follower = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='following')
    followee = models.ForeignKey(Profile, on_delete=models.CASCADE,related_name='followers')

photos/forms.py
from builtins import super

from django import forms

from .models import *


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        exclude = ('user', )


class ProfileForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['Name'].widget = forms.TextInput()

    class Meta:
        model = Profile
        fields = ('Name', 'profile_picture', 'bio')


class CommentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['text'].widget = forms.TextInput()
        self.fields['text'].widget.attrs['placeholder'] = 'Add a comment...'

    class Meta:
        model = Comment
        fields = ('text',)

photos/views.py
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from .models import *
from .forms import *
from django.contrib.auth.decorators import login_required

# Create your views here.


@login_required(login_url='/accounts/login/')
def home(request):
    image_form = PostForm()
    images = Post.objects.all()
    commentform = CommentForm()
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            request.user.profile.post(form)
    return render(request, 'landing.html', locals())


@login_required(login_url='/accounts/login/')
def mine(request):
    images = request.user.profile.posts.all()
    user_object = request.user
    user_images = user_object.profile.posts.all()
    user_saved = [save.photo for save in user_object.profile.saves.all()]
    user_liked = [like.photo for like in user_object.profile.mylikes.all()]
    print(user_liked)
    return render(request, 'myprofile.html', locals())\



@login_required(login_url='/accounts/login/')
def edit(request):
    if request.method == 'POST':
        print(request.FILES)
        new_profile = ProfileForm(
            request.POST,
            request.FILES,
            instance=request.user.profile
        )
        if new_profile.is_valid():
            new_profile.save()
            print(new_profile.fields)
            # print(new_profile.fields.profile_picture)
            return redirect('myaccount')
    else:
        new_profile = ProfileForm(instance=request.user.profile)
    return render(request, 'edit.html', locals())


@login_required(login_url='/accounts/login/')
def user(request, user_id):
    user_object = get_object_or_404(User, pk=user_id)
    if request.user == user_object:
        return redirect('myaccount')
    isfollowing = user_object.profile not in request.user.profile.follows
    user_images = user_object.profile.posts.all()
    user_liked = [like.photo for like in user_object.profile.mylikes.all()]
    return render(request, 'profile.html', locals())


@login_required(login_url='/accounts/login/')
def comment_on(request, post_id):
    commentform = CommentForm()
    post = get_object_or_404(Post, pk=post_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user = request.user.profile
            comment.photo = post
            comment.save()
    # return render(request, 'posts.html', locals())


@login_required(login_url='/accounts/login/')
def like(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    request.user.profile.like(post)
    return JsonResponse(post.count_likes, safe=False)


@login_required(login_url='/accounts/login/')
def save(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    request.user.profile.save_image(post)
    return JsonResponse({}, safe=False)


@login_required(login_url='/accounts/login/')
def unlike(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    request.user.profile.unlike(post)
    return JsonResponse(post.count_likes, safe=False)


@login_required(login_url='/accounts/login/')
def togglefollow(request, user_id):
    target = get_object_or_404(User, pk=user_id).profile
    request.user.profile.togglefollow(target)
    response = [target.followers.count(), target.following.count()]
    return JsonResponse(response, safe=False)


@login_required(login_url='/accounts/login/')
def find(request, name):
    results = Profile.find_profile(name)
    return render(request, 'searchresults.html', locals())

photos/templates/base.html
{% load bootstrap4 %}
{% load static %}

<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="{% static 'css/index.css' %}" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  {%if title%}

  <title>{{title}}</title>
  {% else %}
  <title>Instagram</title>
  {%endif%}

  {% block styles %}
    {% bootstrap_css %}
  {% endblock %}

</head>

<body>
  {% include 'navbar.html' %}
  <div class="container">
    {% block content %}
    {%endblock%}
    <div id="resultsbody">
        <div id="resultsplace">
        </div>
    </div>
  </div>

  {% block scripts %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script
    src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"
    integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU="
    crossorigin="anonymous"></script>
    <script src="{% static 'js/index.js' %}"></script>
    {% bootstrap_javascript %}
  {% endblock %}

</body>

</html>

photos/templates/edit.html
{%extends "base.html" %}
{% load bootstrap4 %}
{% load static %}
{% block content %}
<div class="loginform">
    <form action="{%  url 'edit' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form new_profile %}
        <div class="form-group" style="text-align: center">
            <input type="submit" class="btn btn-primary btn-sm" value="Update">
        </div>
    </form>
</div>
</div>
{% endblock %}

photos/templates/landing.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load utils %}
{% block content %}
<div class="row">
    <div id="images" class="col-md-8 col-12">
        <form action="/" method="post" enctype="multipart/form-data" class="card form-inline">
            {% csrf_token %}
            {{ image_form.image }}
            <div class="uploaddiv">
                <span class="fa-upload" onclick='$("#id_image").click()'></span>
            </div>
            <div class="form-group">
                <input type="submit" class="btn btn-primary btn-sm" value="Upload">
            </div>
        </form>
        {% for image in images %}
        <div class="card">
            <div class="card-body">
                <div class="card-title">
                    <img src="{{image.user.profile_picture.url}}" class="rounded-circle border"
                        alt="{{image.user.user.username}}" width="30" height="30">
                    <a href="{% url 'aboutuser' user_id=image.user.user.id %}">
                        <strong style="color: #333333;cursor: pointer">{{image.user.user.username}}</strong>
                    </a>
                </div>
            </div>
            <div class="card-text">
                <div style="background-image: url({{image.image.url}});background-size: contain;position: sticky"
                    ondblclick="like({{image.id}})">
                    <img src="{{image.image.url}}" style="visibility: hidden;" width="100%" />
                    <span class="likeheart instaicon" id="likeheart{{image.id}}"></span>
                </div>
            </div>
            <div style="padding: 0 16px;">
                <div class="wrapper" onclick="choose({{image.id}})">
                    <span class="{% if user.profile|has_liked:image %}loved{% endif %} love instaglyph"
                        id="likeicon{{image.id}}"></span>
                </div>
                <div class="wrapper">
                    <span class="comment instaglyph"></span>
                </div>
                <div class="wrapper pull-right" onclick="togglesave({{image.id}})">
                    <span class="{% if user.profile|has_saved:image %}saved{% endif %} save instaglyph"
                        id="saveicon{{image.id}}"></span>
                </div>
                <div>
                    <strong><span id="likespan{{image.id}}">{{image.count_likes}}</span>
                        like{{image.count_likes|pluralize}}</strong>
                </div>
                {% if image.get_comments %}
                <div style="border-bottom: solid 1px #bbb;"></div>
                {% endif %}
                {% for comment in image.get_comments|slice:"8" %}
                <p>
                    <strong>{{comment.user.user.username}}</strong> {{comment.text}}
                </p>
                {% endfor %}
                <form action="{% url 'comment' post_id=image.id %}" method="post">
                    {% csrf_token %}
                    <div class="getinput" id="comment{{image.id}}">
                        {{commentform.text}}
                    </div>
                </form>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="card-body col-md-4 d-none d-md-block" id="stories">
        <div class="card-title">
            <img src="{{user.profile.profile_picture.url}}" class="rounded-circle border" alt="{{user.username}}"
                width="50" height="50">
            <a href="{% url 'aboutuser' user_id=user.id %}">
                <strong style="color: #333333;cursor: pointer">{{user.username}}</strong>
            </a>
        </div>
    </div>
</div>
{% endblock %}

photos/templates/myprofile.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{# load utils #}
{% block content %}
<div class="row userbody">
    <div id="userdetails" class="row col-12 mb-2">
        <div class="col-sm-4">
            <img src="{{user_object.profile.profile_picture.url}}" width="152" height="152"
                class="rounded-circle border userimage">
        </div>
        <div class="col-sm-8">
            <div style="margin-bottom: 20px;">
                <h3 style="vertical-align: middle">{{user_object.username}}</h3>
                <a href="{%  url 'edit' %}">
                    <button class="editbtn">
                        <span class="edittext">Edit Profile</span>
                    </button>
                </a>
                <button style="display: contents" class="btn btn-primary" data-toggle="modal" data-target="#logoutmodal">
                    <span class="instaglyph settings"></span>
                </button>
            </div>
            <div style="margin-bottom: 11px;">
                <span class="info"><strong>{{ user_object.profile.posts.count }}</strong> posts</span>
                <span class="info"><strong>{{ user_object.profile.followers.count }}</strong> followers</span>
                <span class="info"><strong>{{ user_object.profile.following.count }}</strong> following</span>
            </div>
            <div>
                <strong>{{ user_object.profile.Name }}</strong>
            </div>
            <div><span>{{ user_object.profile.bio }}</span></div>
        </div>
    </div>
    <ul class="nav" id="my" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" href="#posts" data-toggle="tab" role="tab" aria-controls="posts"
                aria-selected="true">
                Posts
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#saved" data-toggle="tab" role="tab" aria-controls="saved" aria-selected="false">
                Saved
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#liked" data-toggle="tab" role="tab" aria-controls="liked" aria-selected="false">
                Liked
            </a>
        </li>
    </ul>
    <div class="tab-content row col-12" id="myContent">
        <div class="tab-pane fade show active" id="posts" role="tabpanel">
            {% include 'posts.html' with user_images=user_images %}
        </div>
        <div class="tab-pane fade" id="saved" role="tabpanel">
            {% include 'posts.html' with user_images=user_saved %}
        </div>
        <div class="tab-pane fade" id="liked" role="tabpanel">
            {% include 'posts.html' with user_images=user_liked %}
        </div>
        <div class="modal fade" id="logoutmodal" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modalhold modal-content">
                    <div class="modalcontain">
                        <a class="modaloption button" href="/accounts/logout">
                            Log out
                        </a>
                        <a class="modaloption button" data-dismiss="modal">
                            Cancel
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

photos/templates/navbar.html
{% block content %}
<div class="navbar fixed-top">
    <nav class="container">
        <span class="navbar-brand mb-0">
            <a href="/">
                <div id="brand" class="instaicon logo d-none d-sm-block"></div>
                <div class="instaicon mainicon d-block d-sm-none"></div>
            </a>
        </span>
        <form class="mb-0 ml-auto mr-auto" id="searchform">
            <input name="search" autocomplete="off" id="searching" class="form-control d-none d-md-block"
                placeholder=" &#xF002; Search">
            <i class="spinner "></i>
        </form>
        <span class="pull-right">
            <div class="instaicon disc"></div>
            <div class="instaicon like"></div>
            <a href="{% url 'myaccount' %}" class="instaicon pers"></a>
        </span>
    </nav>
</div>
{%endblock%}

photos/templates/posts.html
{% load bootstrap4 %}
{% block content %}

{% for post in user_images %}
<div style="background-image: url({{post.image.url}})" class="post col-6 col-sm-4 col-md-3">
    <div class="photoinfo">
        <div class="realphotoinfo">
            <span class="heartsmall instaicon"></span>
            <span class="infotext">{{post.photolikes.count}}</span>
            <span class="commentsmall instaicon"></span>
            <span class="infotext">{{post.comments.count}}</span>
        </div>
    </div>
</div>
{% endfor %}

{% endblock %}

photos/templates/profile.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load utils %}
{% block content %}
<div class="row userbody">
    <div id="userdetails" class="row col-12 mb-2">
        <div class="col-sm-4">
            <img src="{{user_object.profile.profile_picture.url}}" width="152" height="152"
                class="rounded-circle border userimage">
        </div>
        <div class="col-sm-8">
            <div style="margin-bottom: 20px;">
                <h3 style="vertical-align: middle">{{user_object.username}}</h3>
                <button id="follow" class="editbtn {% if not isfollowing %}d-none{% endif %} btn-primary"
                    onclick="togglefollow({{user_object.id}})">
                    <span class="edittext">Follow</span>
                </button>
                <button id="follown" class="btn {% if isfollowing %}d-none{% endif %} followbtn"
                    onclick="togglefollow({{user_object.id}})">
                    <span class="edittext">Following</span>
                </button>
            </div>
            <div style="margin-bottom: 11px;">
                <span class="info"><strong>{{ user_object.profile.posts.count }}</strong> posts</span>
                <span class="info"><strong id="followers">{{ user_object.profile.followers.count }}</strong>
                    followers</span>
                <span class="info"><strong id="following">{{ user_object.profile.following.count }}</strong>
                    following</span>
            </div>
            <div>
                <strong>{{ user_object.profile.Name }}</strong>
            </div>
            <div><span>{{ user_object.profile.bio }}</span></div>
        </div>
    </div>
    <ul class="nav" id="my" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" href="#posts" data-toggle="tab" role="tab" aria-controls="posts"
                aria-selected="true">
                Posts
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#liked" data-toggle="tab" role="tab" aria-controls="liked" aria-selected="false">
                Liked
            </a>
        </li>
    </ul>
    <div class="tab-content row col-12" id="myContent">
        <div class="tab-pane fade show active" id="posts" role="tabpanel">
            {% include 'posts.html' with user_images=user_images %}
        </div>
        <div class="tab-pane fade" id="liked" role="tabpanel">
            {% include 'posts.html' with user_images=user_liked %}
        </div>
    </div>
</div>
{% endblock %}

photos/templates/searchresults.html
<div class="linkerwrap">
    <div class="linker"></div>
</div>
<div class="searchresults">
    {% for result in results %}
    <div class="searchresult">
        <a href="{%  url 'aboutuser' user_id=result.user.id %}" class="resa">
            <img src="{{result.profile_picture.url}}" class="rounded-circle resimage" width="32" height="32">
            <div class="details">
                <div><strong>{{result.user.username}}</strong></div>
                <span>{{result.Name}}</span>
            </div>
        </a>
    </div>
    {% empty %}
    <div class="searchresult">
        <div class="resa">
            <div class="details">
                <div>No Results Found</div>
                <span>{{result.Name}}</span>
            </div>
        </div>
    </div>
    {% endfor %}
</div>